name:  unit test of feature branches 

on:
 push:
     branches: 
           'feature/*'
jobs:
  run-unit-test:
          runs-on: ubuntu-latest


          steps:
                - name: Checkout
                  uses: actions/checkout@v4.1.7
              
                - name:  unit test
                  run: mvn test
   
